// Generated by PeakRDL-regblock - A free and open-source SystemVerilog generator
//  https://github.com/SystemRDL/PeakRDL-regblock

module adc_acquisition_reg #(
        parameter ID_WIDTH = 1
    ) (
        input wire clk,
        input wire rst,

        input wire s_obi_req,
        output logic s_obi_gnt,
        input wire [4:0] s_obi_addr,
        input wire s_obi_we,
        input wire [3:0] s_obi_be,
        input wire [31:0] s_obi_wdata,
        input wire [ID_WIDTH-1:0] s_obi_aid,
        output logic s_obi_rvalid,
        input wire s_obi_rready,
        output logic [31:0] s_obi_rdata,
        output logic s_obi_err,
        output logic [ID_WIDTH-1:0] s_obi_rid,

        input adc_acquisition_reg_pkg::adc_acquisition_reg__in_t hwif_in,
        output adc_acquisition_reg_pkg::adc_acquisition_reg__out_t hwif_out
    );

    //--------------------------------------------------------------------------
    // CPU Bus interface logic
    //--------------------------------------------------------------------------
    logic cpuif_req;
    logic cpuif_req_is_wr;
    logic [4:0] cpuif_addr;
    logic [31:0] cpuif_wr_data;
    logic [31:0] cpuif_wr_biten;
    logic cpuif_req_stall_wr;
    logic cpuif_req_stall_rd;

    logic cpuif_rd_ack;
    logic cpuif_rd_err;
    logic [31:0] cpuif_rd_data;

    logic cpuif_wr_ack;
    logic cpuif_wr_err;

    // State & holding regs
    logic is_active; // A request is being served (not yet fully responded)
    logic gnt_q; // one-cycle grant for A-channel
    logic rsp_pending; // response ready but not yet accepted by manager
    logic [31:0] rsp_rdata_q;
    logic rsp_err_q;
    logic [$bits(s_obi_rid)-1:0] rid_q;

    // Latch AID on accept to echo back the response
    always_ff @(posedge clk) begin
        if (rst) begin
            is_active <= 1'b0;
            gnt_q <= 1'b0;
            rsp_pending <= 1'b0;
            rsp_rdata_q <= '0;
            rsp_err_q <= 1'b0;
            rid_q <= '0;

            cpuif_req <= '0;
            cpuif_req_is_wr <= '0;
            cpuif_addr <= '0;
            cpuif_wr_data <= '0;
            cpuif_wr_biten <= '0;
        end else begin
            // defaults
            cpuif_req <= 1'b0;
            gnt_q <= s_obi_req & ~is_active;

            // Accept new request when idle
            if (~is_active) begin
                if (s_obi_req) begin
                    is_active <= 1'b1;
                    cpuif_req <= 1'b1;
                    cpuif_req_is_wr <= s_obi_we;
                    cpuif_addr <= {s_obi_addr[4:2], 2'b0};
                    cpuif_wr_data <= s_obi_wdata;
                    rid_q <= s_obi_aid;
                    for (int i = 0; i < 4; i++) begin
                        cpuif_wr_biten[i*8 +: 8] <= {8{ s_obi_be[i] }};
                    end
                end
            end

            // Capture response
            if (is_active && (cpuif_rd_ack || cpuif_wr_ack)) begin
                rsp_pending <= 1'b1;
                rsp_rdata_q <= cpuif_rd_data;
                rsp_err_q <= cpuif_rd_err | cpuif_wr_err;
                // NOTE: Keep 'is_active' asserted until the external R handshake completes
            end

            // Complete external R-channel handshake only if manager ready
            if (rsp_pending && s_obi_rvalid && s_obi_rready) begin
                rsp_pending <= 1'b0;
                is_active <= 1'b0; // free to accept the next request
            end
        end
    end

    // R-channel outputs (held stable while rsp_pending=1)
    assign s_obi_rvalid = rsp_pending;
    assign s_obi_rdata = rsp_rdata_q;
    assign s_obi_err = rsp_err_q;
    assign s_obi_rid = rid_q;

    // A-channel grant (registered one-cycle pulse when we accept a request)
    assign s_obi_gnt = gnt_q;

    logic cpuif_req_masked;

    // Read & write latencies are balanced. Stalls not required
    assign cpuif_req_stall_rd = '0;
    assign cpuif_req_stall_wr = '0;
    assign cpuif_req_masked = cpuif_req
                            & !(!cpuif_req_is_wr & cpuif_req_stall_rd)
                            & !(cpuif_req_is_wr & cpuif_req_stall_wr);

    //--------------------------------------------------------------------------
    // Address Decode
    //--------------------------------------------------------------------------
    typedef struct {
        logic CNTRL;
        logic STATUS;
        logic WRITE_HEAD;
        logic F0_START_ADDR;
        logic F0_END_ADDR;
        logic F1_START_ADDR;
        logic F1_END_ADDR;
    } decoded_reg_strb_t;
    decoded_reg_strb_t decoded_reg_strb;
    logic decoded_err;
    logic [4:0] decoded_addr;
    logic decoded_req;
    logic decoded_req_is_wr;
    logic [31:0] decoded_wr_data;
    logic [31:0] decoded_wr_biten;

    always_comb begin
        automatic logic is_valid_addr;
        automatic logic is_valid_rw;
        is_valid_addr = '1; // No valid address check
        is_valid_rw = '1; // No valid RW check
        decoded_reg_strb.CNTRL = cpuif_req_masked & (cpuif_addr == 5'h0) & cpuif_req_is_wr;
        decoded_reg_strb.STATUS = cpuif_req_masked & (cpuif_addr == 5'h4);
        decoded_reg_strb.WRITE_HEAD = cpuif_req_masked & (cpuif_addr == 5'h8) & !cpuif_req_is_wr;
        decoded_reg_strb.F0_START_ADDR = cpuif_req_masked & (cpuif_addr == 5'hc) & cpuif_req_is_wr;
        decoded_reg_strb.F0_END_ADDR = cpuif_req_masked & (cpuif_addr == 5'h10) & cpuif_req_is_wr;
        decoded_reg_strb.F1_START_ADDR = cpuif_req_masked & (cpuif_addr == 5'h14) & cpuif_req_is_wr;
        decoded_reg_strb.F1_END_ADDR = cpuif_req_masked & (cpuif_addr == 5'h18) & cpuif_req_is_wr;
        decoded_err = '0;
    end

    // Pass down signals to next stage
    assign decoded_addr = cpuif_addr;
    assign decoded_req = cpuif_req_masked;
    assign decoded_req_is_wr = cpuif_req_is_wr;
    assign decoded_wr_data = cpuif_wr_data;
    assign decoded_wr_biten = cpuif_wr_biten;

    //--------------------------------------------------------------------------
    // Field logic
    //--------------------------------------------------------------------------
    typedef struct {
        struct {
            struct {
                logic next;
                logic load_next;
            } RESET_WRITE_HEAD;
        } CNTRL;
        struct {
            struct {
                logic [7:0] next;
                logic load_next;
            } MODE;
            struct {
                logic next;
                logic load_next;
            } F0_FULL;
            struct {
                logic next;
                logic load_next;
            } F1_FULL;
        } STATUS;
        struct {
            struct {
                logic [29:0] next;
                logic load_next;
            } WORD_ADDRESS;
        } WRITE_HEAD;
        struct {
            struct {
                logic [29:0] next;
                logic load_next;
            } WORD_ADDRESS;
        } F0_START_ADDR;
        struct {
            struct {
                logic [29:0] next;
                logic load_next;
            } WORD_ADDRESS;
        } F0_END_ADDR;
        struct {
            struct {
                logic [29:0] next;
                logic load_next;
            } WORD_ADDRESS;
        } F1_START_ADDR;
        struct {
            struct {
                logic [29:0] next;
                logic load_next;
            } WORD_ADDRESS;
        } F1_END_ADDR;
    } field_combo_t;
    field_combo_t field_combo;

    typedef struct {
        struct {
            struct {
                logic value;
            } RESET_WRITE_HEAD;
        } CNTRL;
        struct {
            struct {
                logic [7:0] value;
            } MODE;
            struct {
                logic value;
            } F0_FULL;
            struct {
                logic value;
            } F1_FULL;
        } STATUS;
        struct {
            struct {
                logic [29:0] value;
            } WORD_ADDRESS;
        } WRITE_HEAD;
        struct {
            struct {
                logic [29:0] value;
            } WORD_ADDRESS;
        } F0_START_ADDR;
        struct {
            struct {
                logic [29:0] value;
            } WORD_ADDRESS;
        } F0_END_ADDR;
        struct {
            struct {
                logic [29:0] value;
            } WORD_ADDRESS;
        } F1_START_ADDR;
        struct {
            struct {
                logic [29:0] value;
            } WORD_ADDRESS;
        } F1_END_ADDR;
    } field_storage_t;
    field_storage_t field_storage;

    // Field: adc_acquisition_reg.CNTRL.RESET_WRITE_HEAD
    always_comb begin
        automatic logic [0:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.CNTRL.RESET_WRITE_HEAD.value;
        load_next_c = '0;
        if(decoded_reg_strb.CNTRL && decoded_req_is_wr) begin // SW write 1 set
            next_c = field_storage.CNTRL.RESET_WRITE_HEAD.value | (decoded_wr_data[0:0] & decoded_wr_biten[0:0]);
            load_next_c = '1;
        end else begin // HW Write
            next_c = hwif_in.CNTRL.RESET_WRITE_HEAD.next;
            load_next_c = '1;
        end
        field_combo.CNTRL.RESET_WRITE_HEAD.next = next_c;
        field_combo.CNTRL.RESET_WRITE_HEAD.load_next = load_next_c;
    end
    always_ff @(posedge clk) begin
        if(field_combo.CNTRL.RESET_WRITE_HEAD.load_next) begin
            field_storage.CNTRL.RESET_WRITE_HEAD.value <= field_combo.CNTRL.RESET_WRITE_HEAD.next;
        end
    end
    assign hwif_out.CNTRL.RESET_WRITE_HEAD.value = field_storage.CNTRL.RESET_WRITE_HEAD.value;
    // Field: adc_acquisition_reg.STATUS.MODE
    always_comb begin
        automatic logic [7:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.STATUS.MODE.value;
        load_next_c = '0;
        if(decoded_reg_strb.STATUS && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.STATUS.MODE.value & ~decoded_wr_biten[7:0]) | (decoded_wr_data[7:0] & decoded_wr_biten[7:0]);
            load_next_c = '1;
        end else begin // HW Write
            next_c = hwif_in.STATUS.MODE.next;
            load_next_c = '1;
        end
        field_combo.STATUS.MODE.next = next_c;
        field_combo.STATUS.MODE.load_next = load_next_c;
    end
    always_ff @(posedge clk) begin
        if(rst) begin
            field_storage.STATUS.MODE.value <= 8'h0;
        end else begin
            if(field_combo.STATUS.MODE.load_next) begin
                field_storage.STATUS.MODE.value <= field_combo.STATUS.MODE.next;
            end
        end
    end
    assign hwif_out.STATUS.MODE.value = field_storage.STATUS.MODE.value;
    // Field: adc_acquisition_reg.STATUS.F0_FULL
    always_comb begin
        automatic logic [0:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.STATUS.F0_FULL.value;
        load_next_c = '0;
        if(decoded_reg_strb.STATUS && decoded_req_is_wr) begin // SW write 1 clear
            next_c = field_storage.STATUS.F0_FULL.value & ~(decoded_wr_data[8:8] & decoded_wr_biten[8:8]);
            load_next_c = '1;
        end else begin // HW Write
            next_c = hwif_in.STATUS.F0_FULL.next;
            load_next_c = '1;
        end
        field_combo.STATUS.F0_FULL.next = next_c;
        field_combo.STATUS.F0_FULL.load_next = load_next_c;
    end
    always_ff @(posedge clk) begin
        if(rst) begin
            field_storage.STATUS.F0_FULL.value <= 1'h0;
        end else begin
            if(field_combo.STATUS.F0_FULL.load_next) begin
                field_storage.STATUS.F0_FULL.value <= field_combo.STATUS.F0_FULL.next;
            end
        end
    end
    assign hwif_out.STATUS.F0_FULL.value = field_storage.STATUS.F0_FULL.value;
    // Field: adc_acquisition_reg.STATUS.F1_FULL
    always_comb begin
        automatic logic [0:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.STATUS.F1_FULL.value;
        load_next_c = '0;
        if(decoded_reg_strb.STATUS && decoded_req_is_wr) begin // SW write 1 clear
            next_c = field_storage.STATUS.F1_FULL.value & ~(decoded_wr_data[9:9] & decoded_wr_biten[9:9]);
            load_next_c = '1;
        end else begin // HW Write
            next_c = hwif_in.STATUS.F1_FULL.next;
            load_next_c = '1;
        end
        field_combo.STATUS.F1_FULL.next = next_c;
        field_combo.STATUS.F1_FULL.load_next = load_next_c;
    end
    always_ff @(posedge clk) begin
        if(rst) begin
            field_storage.STATUS.F1_FULL.value <= 1'h0;
        end else begin
            if(field_combo.STATUS.F1_FULL.load_next) begin
                field_storage.STATUS.F1_FULL.value <= field_combo.STATUS.F1_FULL.next;
            end
        end
    end
    assign hwif_out.STATUS.F1_FULL.value = field_storage.STATUS.F1_FULL.value;
    // Field: adc_acquisition_reg.WRITE_HEAD.WORD_ADDRESS
    always_comb begin
        automatic logic [29:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.WRITE_HEAD.WORD_ADDRESS.value;
        load_next_c = '0;
        
        // HW Write
        next_c = hwif_in.WRITE_HEAD.WORD_ADDRESS.next;
        load_next_c = '1;
        field_combo.WRITE_HEAD.WORD_ADDRESS.next = next_c;
        field_combo.WRITE_HEAD.WORD_ADDRESS.load_next = load_next_c;
    end
    always_ff @(posedge clk) begin
        if(rst) begin
            field_storage.WRITE_HEAD.WORD_ADDRESS.value <= 30'h0;
        end else begin
            if(field_combo.WRITE_HEAD.WORD_ADDRESS.load_next) begin
                field_storage.WRITE_HEAD.WORD_ADDRESS.value <= field_combo.WRITE_HEAD.WORD_ADDRESS.next;
            end
        end
    end
    assign hwif_out.WRITE_HEAD.WORD_ADDRESS.value = field_storage.WRITE_HEAD.WORD_ADDRESS.value;
    // Field: adc_acquisition_reg.F0_START_ADDR.WORD_ADDRESS
    always_comb begin
        automatic logic [29:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.F0_START_ADDR.WORD_ADDRESS.value;
        load_next_c = '0;
        if(decoded_reg_strb.F0_START_ADDR && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.F0_START_ADDR.WORD_ADDRESS.value & ~decoded_wr_biten[31:2]) | (decoded_wr_data[31:2] & decoded_wr_biten[31:2]);
            load_next_c = '1;
        end
        field_combo.F0_START_ADDR.WORD_ADDRESS.next = next_c;
        field_combo.F0_START_ADDR.WORD_ADDRESS.load_next = load_next_c;
    end
    always_ff @(posedge clk) begin
        if(rst) begin
            field_storage.F0_START_ADDR.WORD_ADDRESS.value <= 30'h0;
        end else begin
            if(field_combo.F0_START_ADDR.WORD_ADDRESS.load_next) begin
                field_storage.F0_START_ADDR.WORD_ADDRESS.value <= field_combo.F0_START_ADDR.WORD_ADDRESS.next;
            end
        end
    end
    assign hwif_out.F0_START_ADDR.WORD_ADDRESS.value = field_storage.F0_START_ADDR.WORD_ADDRESS.value;
    // Field: adc_acquisition_reg.F0_END_ADDR.WORD_ADDRESS
    always_comb begin
        automatic logic [29:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.F0_END_ADDR.WORD_ADDRESS.value;
        load_next_c = '0;
        if(decoded_reg_strb.F0_END_ADDR && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.F0_END_ADDR.WORD_ADDRESS.value & ~decoded_wr_biten[31:2]) | (decoded_wr_data[31:2] & decoded_wr_biten[31:2]);
            load_next_c = '1;
        end
        field_combo.F0_END_ADDR.WORD_ADDRESS.next = next_c;
        field_combo.F0_END_ADDR.WORD_ADDRESS.load_next = load_next_c;
    end
    always_ff @(posedge clk) begin
        if(rst) begin
            field_storage.F0_END_ADDR.WORD_ADDRESS.value <= 30'h0;
        end else begin
            if(field_combo.F0_END_ADDR.WORD_ADDRESS.load_next) begin
                field_storage.F0_END_ADDR.WORD_ADDRESS.value <= field_combo.F0_END_ADDR.WORD_ADDRESS.next;
            end
        end
    end
    assign hwif_out.F0_END_ADDR.WORD_ADDRESS.value = field_storage.F0_END_ADDR.WORD_ADDRESS.value;
    // Field: adc_acquisition_reg.F1_START_ADDR.WORD_ADDRESS
    always_comb begin
        automatic logic [29:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.F1_START_ADDR.WORD_ADDRESS.value;
        load_next_c = '0;
        if(decoded_reg_strb.F1_START_ADDR && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.F1_START_ADDR.WORD_ADDRESS.value & ~decoded_wr_biten[31:2]) | (decoded_wr_data[31:2] & decoded_wr_biten[31:2]);
            load_next_c = '1;
        end
        field_combo.F1_START_ADDR.WORD_ADDRESS.next = next_c;
        field_combo.F1_START_ADDR.WORD_ADDRESS.load_next = load_next_c;
    end
    always_ff @(posedge clk) begin
        if(rst) begin
            field_storage.F1_START_ADDR.WORD_ADDRESS.value <= 30'h0;
        end else begin
            if(field_combo.F1_START_ADDR.WORD_ADDRESS.load_next) begin
                field_storage.F1_START_ADDR.WORD_ADDRESS.value <= field_combo.F1_START_ADDR.WORD_ADDRESS.next;
            end
        end
    end
    assign hwif_out.F1_START_ADDR.WORD_ADDRESS.value = field_storage.F1_START_ADDR.WORD_ADDRESS.value;
    // Field: adc_acquisition_reg.F1_END_ADDR.WORD_ADDRESS
    always_comb begin
        automatic logic [29:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.F1_END_ADDR.WORD_ADDRESS.value;
        load_next_c = '0;
        if(decoded_reg_strb.F1_END_ADDR && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.F1_END_ADDR.WORD_ADDRESS.value & ~decoded_wr_biten[31:2]) | (decoded_wr_data[31:2] & decoded_wr_biten[31:2]);
            load_next_c = '1;
        end
        field_combo.F1_END_ADDR.WORD_ADDRESS.next = next_c;
        field_combo.F1_END_ADDR.WORD_ADDRESS.load_next = load_next_c;
    end
    always_ff @(posedge clk) begin
        if(rst) begin
            field_storage.F1_END_ADDR.WORD_ADDRESS.value <= 30'h0;
        end else begin
            if(field_combo.F1_END_ADDR.WORD_ADDRESS.load_next) begin
                field_storage.F1_END_ADDR.WORD_ADDRESS.value <= field_combo.F1_END_ADDR.WORD_ADDRESS.next;
            end
        end
    end
    assign hwif_out.F1_END_ADDR.WORD_ADDRESS.value = field_storage.F1_END_ADDR.WORD_ADDRESS.value;

    //--------------------------------------------------------------------------
    // Write response
    //--------------------------------------------------------------------------
    assign cpuif_wr_ack = decoded_req & decoded_req_is_wr;
    // Writes are always granted with no error response
    assign cpuif_wr_err = '0;

    //--------------------------------------------------------------------------
    // Readback
    //--------------------------------------------------------------------------

    logic [4:0] rd_mux_addr;
    assign rd_mux_addr = decoded_addr;

    logic readback_err;
    logic readback_done;
    logic [31:0] readback_data;
    always_comb begin
        automatic logic [31:0] readback_data_var;
        readback_data_var = '0;
        if(rd_mux_addr == 5'h4) begin
            readback_data_var[7:0] = field_storage.STATUS.MODE.value;
            readback_data_var[8] = field_storage.STATUS.F0_FULL.value;
            readback_data_var[9] = field_storage.STATUS.F1_FULL.value;
        end
        if(rd_mux_addr == 5'h8) begin
            readback_data_var[31:2] = field_storage.WRITE_HEAD.WORD_ADDRESS.value;
        end
        readback_data = readback_data_var;
        readback_done = decoded_req & ~decoded_req_is_wr;
        readback_err = '0;
    end

    assign cpuif_rd_ack = readback_done;
    assign cpuif_rd_data = readback_data;
    assign cpuif_rd_err = readback_err;
endmodule
