// Copyright lowRISC contributors (OpenTitan project).
// Licensed under the Apache License, Version 2.0, see LICENSE for details.
// SPDX-License-Identifier: Apache-2.0
//
// Register Package auto-generated by `reggen` containing data structure

package adc_acquisition_reg_pkg;

  // Address widths within the block
  parameter int BlockAw = 2;

  // Number of registers for every interface
  parameter int NumRegs = 1;

  ////////////////////////////
  // Typedefs for registers //
  ////////////////////////////

  typedef struct packed {
    logic [31:0] q;
  } adc_acquisition_reg2hw_adc_aq_rega_reg_t;

  typedef struct packed {
    logic [31:0] d;
    logic        de;
  } adc_acquisition_hw2reg_adc_aq_rega_reg_t;

  // Register -> HW type
  typedef struct packed {
    adc_acquisition_reg2hw_adc_aq_rega_reg_t adc_aq_rega; // [31:0]
  } adc_acquisition_reg2hw_t;

  // HW -> register type
  typedef struct packed {
    adc_acquisition_hw2reg_adc_aq_rega_reg_t adc_aq_rega; // [32:0]
  } adc_acquisition_hw2reg_t;

  // Register offsets
  parameter logic [BlockAw-1:0] ADC_ACQUISITION_ADC_AQ_REGA_OFFSET = 2'h 0;

  // Register index
  typedef enum int {
    ADC_ACQUISITION_ADC_AQ_REGA
  } adc_acquisition_id_e;

  // Register width information to check illegal writes
  parameter logic [3:0] ADC_ACQUISITION_PERMIT [1] = '{
    4'b 1111  // index[0] ADC_ACQUISITION_ADC_AQ_REGA
  };

endpackage
