# Copyright 2022 ETH Zurich and University of Bologna.
# Solderpad Hardware License, Version 0.51, see LICENSE for details.
# SPDX-License-Identifier: SHL-0.51
#
# Nicole Narr <narrn@student.ethz.ch>
# Christopher Reinwardt <creinwar@student.ethz.ch>
# Cyril Koenig <cykoenig@iis.ee.ethz.ch>
# Paul Scheffler <paulsc@iis.ee.ethz.ch>

#############
# Sys Clock #
#############

# 200 MHz input clock
set SYS_TCK 5
create_clock -period $SYS_TCK -name sys_clk [get_ports sys_clk_p]

# SoC clock is generated by clock wizard and its constraints
set SOC_TCK 20.0
set soc_clk [get_clocks -of_objects [get_pins i_clkwiz/clk_soc]]

#############
# ADC Clock #
#############

# adc_clk_i is a free-running clock supplied by the external ADC board over
# Pmod JA. It had no create_clock at all, so check_timing flagged 265
# register/latch pins (the 2-sample packer in adc_acquisition_top.sv plus
# the entire source side of the ADC->SoC cdc_fifo_gray -- data regs, gray
# write pointer, and the sync-chain input flops) as having no clock, meaning
# none of that logic was ever timed, placed, or routed for speed. Measured
# real-hardware ceiling before this constraint was ~28 MHz, which is a
# placement accident, not an architectural limit. Target 100 MHz here.
#
# adc_clk is genuinely asynchronous to soc_clk (crossed only via
# cdc_fifo_gray, whose synchronizer flops already carry the async_reg
# attribute via common_cells/sync.sv, so Vivado treats that first-stage
# capture as intentionally metastable-tolerant rather than a timing
# violation) -- declare it its own async clock group instead of trying to
# relate the two domains.
set ADC_TCK 10.0
create_clock -period $ADC_TCK -name adc_clk [get_ports adc_clk_i]
set_clock_groups -asynchronous -group [get_clocks adc_clk] -group $soc_clk

############
# Switches #
############

set_input_delay -min -clock $soc_clk [expr { $SOC_TCK * 0.10 }] [ \
    get_ports {gpio_i* fan_sw* fetch_en_i}]
set_input_delay -max -clock $soc_clk [expr { $SOC_TCK * 0.35 }] [ \
    get_ports {gpio_i* fan_sw* fetch_en_i}]

set_max_delay [expr { 2 * $SOC_TCK }] -from [get_ports {gpio_i* fan_sw* fetch_en_i}]
set_false_path -hold -from [get_ports {gpio_i* fan_sw* fetch_en_i}]

# fan_pwm (duty-cycle output, human/thermal timescale) and gpio_o (LEDs) have
# no real timing spec to meet -- their SOC_TCK-scaled output_delay budgets
# were an artificial constraint that ate the timing margin needed elsewhere
# (they dominated the entire worst-100 setup path list at 50MHz despite
# neither port having any actual downstream timing requirement). Declared
# false paths outright instead of budgeted, so they stop competing with
# real logic for timing closure as SOC_TCK drops.
set_false_path -to [get_ports fan_pwm]

# LEDs
set_false_path -to [get_ports gpio_o]


###############
# Assign Pins #
###############

# tclint-disable line-length, spacing

## Clock Signal
set_property -dict { PACKAGE_PIN AD11  IOSTANDARD LVDS     } [get_ports { sys_clk_n }]; #IO_L12N_T1_MRCC_33 Sch=sysclk_n
set_property -dict { PACKAGE_PIN AD12  IOSTANDARD LVDS     } [get_ports { sys_clk_p }]; #IO_L12P_T1_MRCC_33 Sch=sysclk_p

## Buttons
set_property -dict { PACKAGE_PIN R19   IOSTANDARD LVCMOS33 } [get_ports { sys_resetn }]; #IO_0_14 Sch=cpu_resetn

## Switches
set_property -dict { PACKAGE_PIN G19   IOSTANDARD LVCMOS12 } [get_ports { gpio_i[0] }]; #IO_0_17 Sch=sw[0]
set_property -dict { PACKAGE_PIN G25   IOSTANDARD LVCMOS12 } [get_ports { gpio_i[1] }]; #IO_25_16 Sch=sw[1]
set_property -dict { PACKAGE_PIN H24   IOSTANDARD LVCMOS12 } [get_ports { gpio_i[2] }]; #IO_L19P_T3_16 Sch=sw[2]
set_property -dict { PACKAGE_PIN K19   IOSTANDARD LVCMOS12 } [get_ports { gpio_i[3] }]; #IO_L6P_T0_17 Sch=sw[3]
set_property -dict { PACKAGE_PIN N19   IOSTANDARD LVCMOS12 } [get_ports { fan_sw[0] }]; #IO_L19P_T3_A22_15 Sch=sw[4]
set_property -dict { PACKAGE_PIN P19   IOSTANDARD LVCMOS12 } [get_ports { fan_sw[1] }]; #IO_25_15 Sch=sw[5]
set_property -dict { PACKAGE_PIN P26   IOSTANDARD LVCMOS33 } [get_ports { fan_sw[2] }]; #IO_L10P_T1_D14_14 Sch=sw[6]
set_property -dict { PACKAGE_PIN P27   IOSTANDARD LVCMOS33 } [get_ports { fetch_en_i }]; #IO_L8P_T1_D11_14 Sch=sw[7]

## LEDs
set_property -dict { PACKAGE_PIN T28   IOSTANDARD LVCMOS33 } [get_ports { gpio_o[0] }]; #IO_L11N_T1_SRCC_14 Sch=led[0]
set_property -dict { PACKAGE_PIN V19   IOSTANDARD LVCMOS33 } [get_ports { gpio_o[1] }]; #IO_L19P_T3_A10_D26_14 Sch=led[1]
set_property -dict { PACKAGE_PIN U30   IOSTANDARD LVCMOS33 } [get_ports { gpio_o[2] }]; #IO_L15N_T2_DQS_DOUT_CSO_B_14 Sch=led[2]
set_property -dict { PACKAGE_PIN U29   IOSTANDARD LVCMOS33 } [get_ports { gpio_o[3] }]; #IO_L15P_T2_DQS_RDWR_B_14 Sch=led[3]
# set_property -dict { PACKAGE_PIN V20   IOSTANDARD LVCMOS33 } [get_ports { led[4] }]; #IO_L19N_T3_A09_D25_VREF_14 Sch=led[4]
# set_property -dict { PACKAGE_PIN V26   IOSTANDARD LVCMOS33 } [get_ports { led[5] }]; #IO_L16P_T2_CSI_B_14 Sch=led[5]
# set_property -dict { PACKAGE_PIN W24   IOSTANDARD LVCMOS33 } [get_ports { led[6] }]; #IO_L20N_T3_A07_D23_14 Sch=led[6]
set_property -dict { PACKAGE_PIN W23   IOSTANDARD LVCMOS33 } [get_ports { status_o }]; #IO_L20P_T3_A08_D24_14 Sch=led[7]

## UART
set_property -dict { PACKAGE_PIN Y23   IOSTANDARD LVCMOS33 } [get_ports { uart_tx_o }]; #IO_L1P_T0_12 Sch=uart_rx_out
set_property -dict { PACKAGE_PIN Y20   IOSTANDARD LVCMOS33 } [get_ports { uart_rx_i }]; #IO_0_12 Sch=uart_tx_in

## ADC (Pmod JA)
set_property -dict { PACKAGE_PIN U27   IOSTANDARD LVCMOS33 } [get_ports { adc_clk_i }]; #IO_L13P_T2_MRCC_14 Sch=ja_p[1]
set_property -dict { PACKAGE_PIN U28   IOSTANDARD LVCMOS33 } [get_ports { adc_data_msb_i }]; #IO_L13N_T2_MRCC_14 Sch=ja_n[1]

## SD Card (Pmod JB, native 4-bit bus)
## SLEW FAST + DRIVE 16 on the driven/bidirectional lines: sharper edges to
## claw back margin at higher SDCLK. DRIVE 24 (max for LVCMOS33) was tried
## and made things worse -- sdcard_test, which passed cleanly at DRIVE 16,
## stopped working entirely at 24. Read as overshoot/ringing on the
## unterminated jumper wiring outweighing the faster edge rate, not a
## marginal signal needing more current -- reverted to 16. See
## project_croc_sdcard_clock_limit memory. sd_cd_ni is card-detect, an
## input-only pin, so SLEW/DRIVE don't apply there.
set_property -dict { PACKAGE_PIN V29   IOSTANDARD LVCMOS33  SLEW FAST  DRIVE 16 } [get_ports { sd_dat_io[3] }]; #Sch=jb[1] (~CS/DAT3)
set_property -dict { PACKAGE_PIN V30   IOSTANDARD LVCMOS33  SLEW FAST  DRIVE 16 } [get_ports { sd_cmd_io    }]; #Sch=jb[2] (MOSI/CMD)
set_property -dict { PACKAGE_PIN V25   IOSTANDARD LVCMOS33  SLEW FAST  DRIVE 16 } [get_ports { sd_dat_io[0] }]; #Sch=jb[3] (MISO/DAT0)
set_property -dict { PACKAGE_PIN W26   IOSTANDARD LVCMOS33  SLEW FAST  DRIVE 16 } [get_ports { sd_clk_o     }]; #Sch=jb[4] (SCK/CLK)
set_property -dict { PACKAGE_PIN T25   IOSTANDARD LVCMOS33  SLEW FAST  DRIVE 16 } [get_ports { sd_dat_io[1] }]; #Sch=jb[7] (DAT1)
set_property -dict { PACKAGE_PIN U25   IOSTANDARD LVCMOS33  SLEW FAST  DRIVE 16 } [get_ports { sd_dat_io[2] }]; #Sch=jb[8] (DAT2)
set_property -dict { PACKAGE_PIN U22   IOSTANDARD LVCMOS33 } [get_ports { sd_cd_ni     }]; #Sch=jb[9] (CD)

## Fan Control
set_property -dict { PACKAGE_PIN W19   IOSTANDARD LVCMOS33 } [get_ports { fan_pwm }]; #IO_25_14 Sch=fan_pwm

## DPTI
# Note: DPTI and DSPI constraints cannot be used in the same design, as they share pins.
set_property -dict { PACKAGE_PIN AD27  IOSTANDARD LVCMOS33 } [get_ports { jtag_tck_i }]; #IO_L11P_T1_SRCC_13 Sch=prog_d0/sck
set_property -dict { PACKAGE_PIN W27   IOSTANDARD LVCMOS33 } [get_ports { jtag_tdi_i }]; #IO_L2P_T0_13 Sch=prog_d1/mosi
set_property -dict { PACKAGE_PIN W28   IOSTANDARD LVCMOS33 } [get_ports { jtag_tdo_o }]; #IO_L2N_T0_13 Sch=prog_d2/miso
set_property -dict { PACKAGE_PIN W29   IOSTANDARD LVCMOS33 } [get_ports { jtag_tms_i }]; #IO_L4P_T0_13 Sch=prog_d3/ss
set_property -dict { PACKAGE_PIN Y29   IOSTANDARD LVCMOS33 } [get_ports { jtag_trst_ni }]; #IO_L4N_T0_13 Sch=prog_d[4]

# tclint-enable line-length, spacing