// Generated by PeakRDL-cheader - A free and open-source header generator
//  https://github.com/SystemRDL/PeakRDL-cheader

#ifndef ADC_ACQUISITION_REG_H
#define ADC_ACQUISITION_REG_H

#ifdef __cplusplus
extern "C" {
#endif
#include <stdint.h>

// reg - adc_acquisition_reg::CNTRL
#define ADC_ACQUISITION_REG__CNTRL__RESET_WRITE_HEAD_bm 0x1
#define ADC_ACQUISITION_REG__CNTRL__RESET_WRITE_HEAD_bp 0
#define ADC_ACQUISITION_REG__CNTRL__RESET_WRITE_HEAD_bw 1

// reg - adc_acquisition_reg::STATUS
#define ADC_ACQUISITION_REG__STATUS__MODE_bm 0xff
#define ADC_ACQUISITION_REG__STATUS__MODE_bp 0
#define ADC_ACQUISITION_REG__STATUS__MODE_bw 8
#define ADC_ACQUISITION_REG__STATUS__MODE_reset 0x0
#define ADC_ACQUISITION_REG__STATUS__F0_FULL_bm 0x100
#define ADC_ACQUISITION_REG__STATUS__F0_FULL_bp 8
#define ADC_ACQUISITION_REG__STATUS__F0_FULL_bw 1
#define ADC_ACQUISITION_REG__STATUS__F0_FULL_reset 0x0
#define ADC_ACQUISITION_REG__STATUS__F1_FULL_bm 0x200
#define ADC_ACQUISITION_REG__STATUS__F1_FULL_bp 9
#define ADC_ACQUISITION_REG__STATUS__F1_FULL_bw 1
#define ADC_ACQUISITION_REG__STATUS__F1_FULL_reset 0x0

// reg - adc_acquisition_reg::WRITE_HEAD
#define ADC_ACQUISITION_REG__WRITE_HEAD__WORD_ADDRESS_bm 0xfffffffc
#define ADC_ACQUISITION_REG__WRITE_HEAD__WORD_ADDRESS_bp 2
#define ADC_ACQUISITION_REG__WRITE_HEAD__WORD_ADDRESS_bw 30
#define ADC_ACQUISITION_REG__WRITE_HEAD__WORD_ADDRESS_reset 0x0

// reg - adc_acquisition_reg::address_config_r
#define ADC_ACQUISITION_REG__ADDRESS_CONFIG_R__WORD_ADDRESS_bm 0xfffffffc
#define ADC_ACQUISITION_REG__ADDRESS_CONFIG_R__WORD_ADDRESS_bp 2
#define ADC_ACQUISITION_REG__ADDRESS_CONFIG_R__WORD_ADDRESS_bw 30
#define ADC_ACQUISITION_REG__ADDRESS_CONFIG_R__WORD_ADDRESS_reset 0x0

// addrmap - adc_acquisition_reg
typedef struct __attribute__ ((__packed__)) {
    uint32_t CNTRL;
    uint32_t STATUS;
    uint32_t WRITE_HEAD;
    uint32_t F0_START_ADDR;
    uint32_t F0_END_ADDR;
    uint32_t F1_START_ADDR;
    uint32_t F1_END_ADDR;
} adc_acquisition_reg_t;



#ifdef __cplusplus
}
#endif

#endif /* ADC_ACQUISITION_REG_H */
